# Import

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/Users/abhisheksharma/mambaforge/lib/python3.9/site-packages/numpy/__init__.py'>

# Creating Arrays

Creating an array of zeros.

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Creating an array of ones.

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Creating an array of specified element.

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Creating an array with iterators.

In [7]:
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.array(range(1,11))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Accessing and updating an array element.

In [11]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [12]:
a[2]

3

In [13]:
a[2] = 30
a

array([ 1,  2, 30,  4,  5])

Creating an array by passing a range.

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [18]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [29]:
np.logspace(1, 10, 10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

# Multi-dimensional Arrays

2-D array of zeros, ones and specified element

In [30]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
np.full((5, 2), 2.5)

array([[2.5, 2.5],
       [2.5, 2.5],
       [2.5, 2.5],
       [2.5, 2.5],
       [2.5, 2.5]])

In [33]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Accessing and updaing elements in a 2-D array

In [34]:
n[0,1]

2

In [35]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [36]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [37]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

# Randomly Generated Arrays

Setting a seed for reproducibility of pseudorandom generation.

In [39]:
np.random.seed(42)

Generating from uniform distribution.

In [41]:
np.random.rand(5,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

Generating from normal distribution.

In [42]:
np.random.randn(5,2)

array([[-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024],
       [-1.72491783, -0.56228753],
       [-1.01283112,  0.31424733]])

Generating integers between specified range.

In [43]:
np.random.randint(low=0, high=100, size=(5,2))

array([[91, 59],
       [79, 14],
       [61, 61],
       [46, 61],
       [50, 54]])

# Elementwise Operations

In [45]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [46]:
a + 1

array([1, 2, 3, 4, 5])

In [47]:
a * 2

array([0, 2, 4, 6, 8])

In [48]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [49]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [50]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

# Comparison Operators

In [51]:
a

array([0, 1, 2, 3, 4])

In [53]:
a >= 2

array([False, False,  True,  True,  True])

In [54]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [55]:
a > b

array([False, False,  True,  True,  True])

In [57]:
a[a > b]

array([2, 3, 4])

# Summarizing Operations

In [58]:
a

array([0, 1, 2, 3, 4])

In [59]:
a.std()

1.4142135623730951

In [60]:
a.mean()

2.0

In [61]:
a.min()

0

In [62]:
a.max()

4