In [1]:
import numpy as np

# Vector Operations

In [2]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [3]:
u * 2

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [5]:
u + v

array([3, 4, 5, 8])

In [6]:
u - v

array([1, 4, 5, 4])

In [7]:
u * v

array([ 2,  0,  0, 12])

In [8]:
v / u

array([0.5       , 0.        , 0.        , 0.33333333])

# Multiplication

In [68]:
v.shape[0]

4

In [69]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.
    for i in range(n):
        result += u[i] * v[i]
    return result

In [70]:
vector_vector_multiplication(u, v)

14.0

In [71]:
u.dot(v)

14

In [72]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [73]:
U.shape

(3, 4)

In [74]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    n = U.shape[0]
    result = np.zeros(n)
    for i in range(n):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

In [75]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [76]:
U.dot(v)

array([14,  5,  5])

In [77]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [78]:
V.shape

(4, 3)

In [79]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    n = U.shape[0]
    c = V.shape[1]
    result = np.zeros((n, c))
    for i in range(c):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    return result

In [80]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [82]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# Indentity

In [83]:
I = np.eye(3)

In [84]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

# Inverse

In [86]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [87]:
Vs = V[[1, 2, 3]]

In [88]:
Vs

array([[0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [89]:
Vinv = np.linalg.inv(Vs)

In [91]:
Vinv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])